import 'modern-normalize/modern-normalize.css';
import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const gilroy = localFont({
  src: [
    {
      path: '../public/fonts/Gilroy-Medium.woff2', 
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Gilroy-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-gilroy',
  display: 'swap',
});

const sfPro = localFont({
  src: [
    {
      path: '../public/fonts/SFProText-Semibold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-sf-pro',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Read journey app",
  description: "Application to create personal books collection and track reading progressGenerated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gilroy.variable} ${sfPro.variable}`}>
      <body>{children}</body>
    </html>
  );
}
